AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A LINE bot that will guide you to the port where you can rent a bicycle.
Resources:
  LineWebhook:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        info:
          title: Line webhook
          description: Line webhook
          version: 0.1.0
        schemes:
          - https
        basePath: "/"
        paths:
          /webhook:
            post:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                httpMethod: POST
                type: aws
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AvailableBikeBot.Arn}/invocations
        definitions:
          Empty:
            type: "object"
            title: "Empty Schema"

  AvailableBikeBot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      Runtime: nodejs6.10
      Description: A LINE bot that will guide you to the port where you can rent a bicycle.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          MESSAGE_API_TOKEN: ""
      Events:
        Webhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId:
              Ref: LineWebhook

Outputs:
  ApiUrl:
    Value: !Sub https://${LineWebhook}.execute-api.${AWS::Region}.amazonaws.com/prod/webhook
